# Generated by Django 5.2.5 on 2025-08-25 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='created_at',
            new_name='criada_em',
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='created_by',
            new_name='criada_por',
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='modified_at',
            new_name='modificada_em',
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='name',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='description',
            new_name='sobre',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='priority',
        ),
        migrations.AddField(
            model_name='lead',
            name='prioridade',
            field=models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta')], default='media', max_length=10),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('novo', 'Novo'), ('contactada', 'Contactada'), ('convertida', 'Convertida'), ('perdida', 'Perdida')], default='novo', max_length=10),
        ),
    ]
