# Generated by Django 5.2.5 on 2025-08-28 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0002_rename_created_at_lead_criada_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='convertida_para_client',
            field=models.BooleanField(default=False),
        ),
    ]
