# Generated by Django 5.2.5 on 2025-09-11 19:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0005_alter_lead_options_leadcomments'),
        ('team', '0002_rename_members_team_membros_alter_team_criado_por'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LeadComments',
            new_name='Comment',
        ),
    ]
