# Generated by Django 5.2.5 on 2025-09-11 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0006_rename_leadcomments_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='criada_em',
            new_name='criado_em',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='criada_por',
            new_name='criado_por',
        ),
    ]
