# Generated by Django 5.2.5 on 2025-09-11 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0007_rename_criada_em_comment_criado_em_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
