# Generated by Django 5.2.5 on 2025-08-29 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='criada_em',
            new_name='criado_em',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='criada_por',
            new_name='criado_por',
        ),
    ]
