# Generated by Django 5.2.5 on 2025-08-29 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_rename_criada_em_client_criado_em_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='modificada_em',
            new_name='modificado_em',
        ),
    ]
