# Generated by Django 5.2.5 on 2025-09-11 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_client_team'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ('nome',)},
        ),
    ]
