# Generated by Django 5.2.5 on 2025-08-30 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='members',
            new_name='membros',
        ),
        migrations.AlterField(
            model_name='team',
            name='criado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams_criados', to=settings.AUTH_USER_MODEL),
        ),
    ]
